/* 
*/

#ifndef ADBKeyCode_h
#define ADBKeyCode_h

/* Ignore code for key code translation */
#define ADB_KEY_IGNORE  0xBB

/* General defines of comms codes */
/* Command or response */
#define ADB_KC_RESEND   ADB_KEY_IGNORE //0xFE
#define ADB_KC_ACK      ADB_KEY_IGNORE //0xFA
#define ADB_KC_ECHO     ADB_KEY_IGNORE //0xEE
/* Responses */
#define ADB_KC_BAT      ADB_KEY_IGNORE //0xAA
// Actually buffer overrun
#define ADB_KC_OVERRUN  ADB_KEY_IGNORE //0xFF
// Below is general error code
#define ADB_KC_ERROR    ADB_KEY_IGNORE //0xFC
#define ADB_KC_KEYBREAK ADB_KEY_IGNORE //0xF0
#define ADB_KC_EXTEND1  ADB_KEY_IGNORE //0xE1
#define ADB_KC_EXTEND   ADB_KEY_IGNORE //0xE0
/* Commands */
#define ADB_KC_RESET    ADB_KEY_IGNORE //0xFF
#define ADB_KC_DEFAULTS ADB_KEY_IGNORE //0xF6
#define ADB_KC_DISABLE  ADB_KEY_IGNORE //0xF5
#define ADB_KC_ENABLE   ADB_KEY_IGNORE //0xF4
#define ADB_KC_RATE     ADB_KEY_IGNORE //0xF3
#define ADB_KC_READID   ADB_KEY_IGNORE //0xF2
#define ADB_KC_SCANCODE ADB_KEY_IGNORE //0xF0
#define ADB_KC_LOCK     ADB_KEY_IGNORE //0xED

/* Single Byte Key Codes */
#define ADB_KC_NUM      ADB_KEY_IGNORE //0x77
#define ADB_KC_SCROLL   ADB_KEY_IGNORE //0x7E
#define ADB_KC_CAPS     0x39
#define ADB_KC_L_SHIFT  0x38
#define ADB_KC_R_SHIFT  0x7B
/* This is Left CTRL and ALT but Right version is in E0 with same code */
#define ADB_KC_CTRL     0x36
#define ADB_KC_ALT      0x3A
/* Generated by some keyboards by ALT and PRTSCR */
#define ADB_KC_SYSRQ    ADB_KEY_IGNORE //0x84
#define ADB_KC_ESC      0x35
#define ADB_KC_BS       0x33
#define ADB_KC_TAB      0x30
#define ADB_KC_ENTER    0x24
#define ADB_KC_SPACE    0x31
#define ADB_KC_KP0      0x52
#define ADB_KC_KP1      0x53
#define ADB_KC_KP2      0x54
#define ADB_KC_KP3      0x55
#define ADB_KC_KP4      0x56
#define ADB_KC_KP5      0x57
#define ADB_KC_KP6      0x58
#define ADB_KC_KP7      0x59
#define ADB_KC_KP8      0x5B
#define ADB_KC_KP9      0x5C
#define ADB_KC_KP_DOT   0x41
#define ADB_KC_KP_PLUS  0x45
#define ADB_KC_KP_MINUS 0x4E
#define ADB_KC_KP_TIMES 0x43
/* Some keyboards have an '=' on right keypad */
#define ADB_KC_KP_EQUAL ADB_KEY_IGNORE //0x0F
#define ADB_KC_0        0x1D
#define ADB_KC_1        0x12
#define ADB_KC_2        0x13
#define ADB_KC_3        0x14
#define ADB_KC_4        0x15
#define ADB_KC_5        0x17
#define ADB_KC_6        0x16
#define ADB_KC_7        0x1A
#define ADB_KC_8        0x1C
#define ADB_KC_9        0x19
#define ADB_KC_APOS     0x27
#define ADB_KC_COMMA    0x2B
#define ADB_KC_MINUS    0x1B
#define ADB_KC_DOT      0x2F
#define ADB_KC_DIV      0x2C
/* Single quote or back apostrophe */
#define ADB_KC_SINGLE   0x32
#define ADB_KC_A        0x00
#define ADB_KC_B        0x0B
#define ADB_KC_C        0x08
#define ADB_KC_D        0x02
#define ADB_KC_E        0x0E
#define ADB_KC_F        0x03
#define ADB_KC_G        0x05
#define ADB_KC_H        0x04
#define ADB_KC_I        0x22
#define ADB_KC_J        0x26
#define ADB_KC_K        0x28
#define ADB_KC_L        0x25
#define ADB_KC_M        0x2E
#define ADB_KC_N        0x2D
#define ADB_KC_O        0x1F
#define ADB_KC_P        0x23
#define ADB_KC_Q        0x0C
#define ADB_KC_R        0x0F
#define ADB_KC_S        0x01
#define ADB_KC_T        0x11
#define ADB_KC_U        0x20
#define ADB_KC_V        0x09
#define ADB_KC_W        0x0D
#define ADB_KC_X        0x07
#define ADB_KC_Y        0x10
#define ADB_KC_Z        0x06
#define ADB_KC_SEMI     0x29
#define ADB_KC_BACK     0x2A
// Extra key left of Z on 102 keyboards
#define ADB_KC_EUROPE2  ADB_KEY_IGNORE //0x61
#define ADB_KC_OPEN_SQ  0x21
#define ADB_KC_CLOSE_SQ 0x1E
#define ADB_KC_EQUAL    0x18
#define ADB_KC_F1       0x7A
#define ADB_KC_F2       0x78
#define ADB_KC_F3       0x63
#define ADB_KC_F4       0x76
#define ADB_KC_F5       0x60
#define ADB_KC_F6       0x61
#define ADB_KC_F7       0x62
#define ADB_KC_F8       0x64
#define ADB_KC_F9       0x65
#define ADB_KC_F10      0x6D
#define ADB_KC_F11      0x67
#define ADB_KC_F12      0x6F
#define ADB_KC_F13      ADB_KEY_IGNORE //0X08
#define ADB_KC_F14      ADB_KEY_IGNORE //0X10
#define ADB_KC_F15      ADB_KEY_IGNORE //0X18
#define ADB_KC_F16      ADB_KEY_IGNORE //0X20
#define ADB_KC_F17      ADB_KEY_IGNORE //0X28
#define ADB_KC_F18      ADB_KEY_IGNORE //0X30
#define ADB_KC_F19      ADB_KEY_IGNORE //0X38
#define ADB_KC_F20      ADB_KEY_IGNORE //0X40
#define ADB_KC_F21      ADB_KEY_IGNORE //0X48
#define ADB_KC_F22      ADB_KEY_IGNORE //0X50
#define ADB_KC_F23      ADB_KEY_IGNORE //0X57
#define ADB_KC_F24      ADB_KEY_IGNORE //0X5F
#define ADB_KC_KP_COMMA ADB_KEY_IGNORE //0X6D
#define ADB_KC_INTL1    ADB_KEY_IGNORE //0X51
#define ADB_KC_INTL2    ADB_KEY_IGNORE //0X13
#define ADB_KC_INTL3    ADB_KEY_IGNORE //0X6A
#define ADB_KC_INTL4    ADB_KEY_IGNORE //0X64
#define ADB_KC_INTL5    ADB_KEY_IGNORE //0X67
#define ADB_KC_LANG1    ADB_KEY_IGNORE //0XF2
#define ADB_KC_LANG2    ADB_KEY_IGNORE //0XF1
#define ADB_KC_LANG3    ADB_KEY_IGNORE //0X63
#define ADB_KC_LANG4    ADB_KEY_IGNORE //0X62
#define ADB_KC_LANG5    ADB_KEY_IGNORE //0X5F

/* Extended key codes E0 table for two byte codes */
/* PS2_CTRL and PS2_ALT Need using in any table for the right keys */
/* first is special case for PRTSCR not always used so ignored by decoding */
#define ADB_KC_IGNORE   ADB_KEY_IGNORE //0x12
#define ADB_KC_PRTSCR   ADB_KEY_IGNORE //0x7C
/* Sometimes called windows key */
#define ADB_KC_L_GUI    0x37
#define ADB_KC_R_GUI    0x37
#define ADB_KC_MENU     ADB_KEY_IGNORE //0x2F
/* Break is CTRL + PAUSE generated inside keyboard */
#define ADB_KC_BREAK    ADB_KEY_IGNORE //0x7E
#define ADB_KC_HOME     0x73
#define ADB_KC_END      0x77
#define ADB_KC_PGUP     0x74
#define ADB_KC_PGDN     0x79
#define ADB_KC_L_ARROW  0x3B
#define ADB_KC_R_ARROW  0x3C
#define ADB_KC_UP_ARROW 0x3E
#define ADB_KC_DN_ARROW 0x3D
#define ADB_KC_INSERT   0x72
#define ADB_KC_DELETE   0x75
#define ADB_KC_KP_ENTER 0x4C
#define ADB_KC_KP_DIV   0x4B
#define ADB_KC_NEXT_TR  ADB_KEY_IGNORE //0X4D
#define ADB_KC_PREV_TR  ADB_KEY_IGNORE //0X15
#define ADB_KC_STOP     ADB_KEY_IGNORE //0X3B
#define ADB_KC_PLAY     ADB_KEY_IGNORE //0X34
#define ADB_KC_MUTE     ADB_KEY_IGNORE //0X23
#define ADB_KC_VOL_UP   ADB_KEY_IGNORE //0X32
#define ADB_KC_VOL_DN   ADB_KEY_IGNORE //0X21
#define ADB_KC_MEDIA    ADB_KEY_IGNORE //0X50
#define ADB_KC_EMAIL    ADB_KEY_IGNORE //0X48
#define ADB_KC_CALC     ADB_KEY_IGNORE //0X2B
#define ADB_KC_COMPUTER ADB_KEY_IGNORE //0X40
#define ADB_KC_WEB_SEARCH  ADB_KEY_IGNORE //0X10
#define ADB_KC_WEB_HOME    ADB_KEY_IGNORE //0X3A
#define ADB_KC_WEB_BACK    ADB_KEY_IGNORE //0X38
#define ADB_KC_WEB_FORWARD ADB_KEY_IGNORE //0X30
#define ADB_KC_WEB_STOP    ADB_KEY_IGNORE //0X28
#define ADB_KC_WEB_REFRESH ADB_KEY_IGNORE //0X20
#define ADB_KC_WEB_FAVOR   ADB_KEY_IGNORE //0X18
#define ADB_KC_POWER    ADB_KEY_IGNORE //0X37
#define ADB_KC_SLEEP    ADB_KEY_IGNORE //0X3F
#define ADB_KC_WAKE     ADB_KEY_IGNORE //0X5E
#endif
